apiVersion: v1
kind: Service
metadata:
  name: interval-generator-service
  namespace: default
  labels:
    app: interval-generator
spec:
  type: ClusterIP
  selector:
    app: interval-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  sessionAffinity: None
